### ISSUE TITLE
Parser Error: The identifier "VoxelInstancer" isn't a valid type (not a script or class), or couldn't be found on base "self".

### ISSUE THREAD

**Issue by PrawnThegr8** [Zylann/solar_system_demo#2]
FIX THIS

**Comment by Zylann** [comment]
This error is very likely because you are using the wrong version of the module. `VoxelInstancer` should exist.

**Comment by PrawnThegr8** [comment]
> This error is very likely because you are using an old version of the module. `VoxelInstancer` should exist.

can you send the latest version
pls

**Comment by PrawnThegr8** [comment]
pls its important

**Comment by PrawnThegr8** [comment]
im sry if the caps felt rude, it was a typo

**Comment by Zylann** [comment]
The latest CI build is here https://github.com/Zylann/godot_voxel/actions/runs/1263069000
The `tools` one is an editor build, the other is a release build without editor.

This stuff is indicated in the docs btw https://voxel-tools.readthedocs.io/en/latest/getting_the_module/

**Comment by PrawnThegr8** [comment]
tysm

**Comment by PrawnThegr8** [comment]
btw you are so cool, i love ur vids, can you shout out trysome code, its my yt channel

**Comment by PrawnThegr8** [comment]
imma closing the issue now, tysm again
