### ISSUE TITLE
Parser Error: Could not find type "VoxelLodTerrain" in the current scope.

### ISSUE THREAD

**Issue by diybl** [Zylann/solar_system_demo#9]
when i click the start button 
show the error:
Parser Error: Could not find type "VoxelLodTerrain" in the current scope.

**Comment by diybl** [comment]
my godot version 4.0.2

**Comment by MGilleronFJ** [comment]
You have to use a version of godot that includes the voxel module, see https://github.com/Zylann/solar_system_demo#dependencies
